### ISSUE TITLE
你确定你那是能成功打包的？跟IDE有关？

### ISSUE THREAD

**Issue by dean-coding** [lxchinesszz/multi-boluome#2]
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /C:/Users/Administrator/Desktop/multi-boluome/dao/src/main/java/iflyer/dao/UserRepo.java:[5,20] 程序包iflyer.model不存在
[ERROR] /C:/Users/Administrator/Desktop/multi-boluome/dao/src/main/java/iflyer/dao/UserRepo.java:[7,50] 找不到符号
  符号: 类 User
[INFO] 2 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] multi-boluome ...................................... SUCCESS [  4.837 s]
[INFO] domain ............................................. SUCCESS [  2.133 s]
[INFO] dao ................................................ FAILURE [  0.716 s]
[INFO] service ............................................ SKIPPED
[INFO] web ................................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.405 s
[INFO] Finished at: 2017-12-24T19:37:42+08:00
[INFO] Final Memory: 37M/130M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project dao: Compilation failure: Compilation failure:
[ERROR] /C:/Users/Administrator/Desktop/multi-boluome/dao/src/main/java/iflyer/dao/UserRepo.java:[5,20] 程序包iflyer.model不存在
[ERROR] /C:/Users/Administrator/Desktop/multi-boluome/dao/src/main/java/iflyer/dao/UserRepo.java:[7,50] 找不到符号
[ERROR] 符号: 类 User
[ERROR] -> [Help 1]

**Comment by dean-coding** [comment]
我用eclipse编译了一下，然后又直接用maven-cmd编译了一下都是这样的结果

**Comment by lxchinesszz** [comment]
缺少的模块,像平时我们添加依赖坐标一样,放到dao层就好了。因为我是用idea设置。可能你的环境跟我不一样，你需要手动去依赖
